### ISSUE TITLE
Watchlist

### ISSUE THREAD

**Issue by peteryu6688** [atimathong/onlineauction#25]

**Comment by atimathong** [comment]
@peteryu6688 

I have created a watchlist button for at the product display page and the product detail page. Therefore, there are watchlist buttons at 2 locations now and the user can click on either of them.

1. 1st location
<img width="988" alt="image" src="https://user-images.githubusercontent.com/115724731/200176898-49f8b57c-d4c1-40b7-b0e9-ea7901d4906c.png">

2. 2nd location
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/115724731/200176918-c6007cc3-3054-4dd4-b622-c893d00a6fd2.png">


**Expected Features**

1. When the user click on the watchlist button on either page, that item must be added to our database specifically to a particular users.
2. If there is a duplication in user's watchlist, for example you already add Body Wash to your watchlist, but you forgot so  you add it again, our system should not add Body Wash to the database since it already exist. In other words, the pair of user_ID and item_ID added to watchlist must be unique.
3. Build the watchlist page. After the user clicks on **_My Watchlist_** tab on the Nav bar, he/she must be able to see a table that contains the list of product they have added to the watchlist.

You could make the page in any form you like but make sure it contains basic information to identify each product.

<img width="269" alt="image" src="https://user-images.githubusercontent.com/115724731/200177260-ec91e17f-f235-46eb-a37e-dd946cf5e804.png">
